import Head from 'next/head'
import { SwitchSelectors } from '../components/switch-selectors'
import { SwitchComplex } from '../components/switch-complex'
import { SwitchComplexClsx } from '../components/switch-complex-clsx'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col gap-10 align-center justify-center">
        <SwitchSelectors />
        <SwitchComplex />
        <SwitchComplexClsx />
      </main>
    </div>
  )
}
